### ISSUE TITLE
Consider include the implementation of virtual environment in the installation guide (README.md))

### ISSUE THREAD

**Issue by D7NAMITE** [PeanutPK/Diabetes-Checker#1]
Hi,
This is just a recommendation, but it would be great to include the virtual environment setup for your project.

Here is the [article](https://devhub.in.th/blog/python-virtual-environment-venv) you might find useful.

Also, 
consider putting in the
```cd Diabetes-Analysis```
after the repo cloning. From that, you'll be able to install the requirements package.

Keep up the good work 👍🏽

![image](https://github.com/PeanutPK/Diabetes-Analysis/assets/33195267/22515b8e-c034-4bb7-9de6-a467b73575fb)

**Comment by PeanutPK** [comment]
I updated my readme thanks
